name: Newbies

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Thanks for creating an issue!"
        pr-message: "Thankyou; we'll look at this ASAP. Make sure your PR explains the changes you've made so we can deal with it swiftly."
